high_level_planner:
  ros__parameters:
    expected_planner_frequency: 1.0
    set_orientation: True  # Set intermediate orientations along path from simple 2D planner
    distance_threshold: 0.25   # Distance in meters from final position to determine success
    planner_plugin: 'GridBased'
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
    smoother_type: 'SimpleSmoother'
    simple_smoother:
        tolerance: 2e-10
        max_its: 1001
        w_data: 0.21
        w_smooth: 0.31
        do_refinement: true
        refinement_num: 2
        smoother_timeout: 2.5

high_level_planner_rclcpp_node:
  ros__parameters:
    use_sim_time: True
